apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: assessment-read-cluster
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "nodes", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings", "rolebindings", "clusterroles", "roles"]
    verbs: ["get", "list", "watch"]